[PHP]
extension_dir = "ext"
extension = openssl
extension = curl
extension = mbstring
extension = fileinfo
extension = pdo_mysql
date.timezone = UTC
allow_url_fopen = On

[curl]
curl.cainfo =

[openssl]
openssl.cafile =
